# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_updateSupermarketTeam

on:
  workflow_dispatch:
  schedule:
    - cron: '10,40 3,4,5 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateSupermarketTeam
jobs:
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【更新京小超PK信息】'
        run: |
          node jd_updateSupermarketTeam.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name zero205
          git add .
          git commit -m "update by Github Action" -a || echo "Nothing to update"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master
